### ISSUE TITLE
PyTorch version issue

### ISSUE THREAD

**Issue by pcoursaux** [unbounce/pytorch-tree-lstm#11]
Hi,

I think the PyTorch versions specified in the REAME are not correct.
When I run `example_usage.py` with either PyTorch 0.4.0 or PyTorch 1.0.1 I have the error `module 'torch' has no attribute 'unique_consecutive'
However it works with PyTorch 1.1.0
